# Generated by Django 3.0.7 on 2020-06-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamdetail',
            name='phone_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
