# Generated by Django 3.0.4 on 2020-06-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0003_contactdetail_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetail',
            old_name='name',
            new_name='full_name',
        ),
    ]
